#!/usr/bin/env python3
"""Write the baseline system prompt to prompts/ so it is readable and diffable."""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from triage.baseline import VERSION, system_prompt
from triage.llm import REPO_ROOT

dest = REPO_ROOT / "prompts" / f"{VERSION}.md"
dest.parent.mkdir(exist_ok=True)
dest.write_text(
    "<!-- Generated by scripts/render_prompt.py from src/triage/baseline.py. "
    "Edit the Python, not this file. -->\n\n" + system_prompt()
)
print(f"Wrote {dest.relative_to(REPO_ROOT)} ({len(system_prompt())} chars)")
